spring.application.name=filmserie-api
spring.datasource.url=jdbc:postgresql://ep-misty-band-aid147x1-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_wKW08gRcSvhY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080